import React, { useState } from 'react';
import { CaseFile, CaseTask, TaskType, ActivityLog } from '../types';
import { getWorkflowProgress, generateInitialWorkflowTasks, generateReminderTasks, WorkflowStageProgress } from '../services/workflowEngine';

interface CaseWorkflowProps {
  caseData: CaseFile;
  onUpdateCase: (c: CaseFile) => void;
}

function addActivity(c: CaseFile, message: string): CaseFile {
  const log: ActivityLog = {
    id: Math.random().toString(36).substr(2, 9),
    type: 'system',
    message,
    timestamp: new Date().toISOString(),
  };
  return { ...c, activityLog: [log, ...(c.activityLog || [])] };
}

function addDays(days: number): string {
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
}

const STATUS_COLORS: Record<WorkflowStageProgress['status'], string> = {
  complete: 'bg-emerald-500 text-white border-emerald-500',
  active: 'bg-blue-600 text-white border-blue-600',
  pending: 'bg-white text-slate-400 border-slate-200',
  blocked: 'bg-white text-slate-300 border-slate-100',
};

const STATUS_CONNECTOR: Record<WorkflowStageProgress['status'], string> = {
  complete: 'bg-emerald-400',
  active: 'bg-gradient-to-r from-emerald-400 to-blue-300',
  pending: 'bg-slate-100',
  blocked: 'bg-slate-100',
};

export const CaseWorkflow: React.FC<CaseWorkflowProps> = ({ caseData, onUpdateCase }) => {
  const [expandedStage, setExpandedStage] = useState<string | null>(null);
  const [completingItem, setCompletingItem] = useState<string | null>(null);

  const stages = getWorkflowProgress(caseData);
  const totalItems = stages.reduce((s, st) => s + st.totalItems, 0);
  const completedItems = stages.reduce((s, st) => s + st.completedItems, 0);
  const overallPct = totalItems > 0 ? Math.round((completedItems / totalItems) * 100) : 0;

  const handleGenerateTasks = () => {
    const newTasks = generateInitialWorkflowTasks(caseData);
    const reminders = generateReminderTasks(caseData);
    const all = [...newTasks, ...reminders];
    if (all.length === 0) return;
    let updated = {
      ...caseData,
      workflowInitialized: true,
      tasks: [...(caseData.tasks || []), ...all],
    };
    updated = addActivity(updated, `${all.length} workflow task(s) generated`);
    onUpdateCase(updated);
  };

  const handleCheckReminders = () => {
    const reminders = generateReminderTasks(caseData);
    if (reminders.length === 0) {
      alert('No new reminders needed at this time.');
      return;
    }
    let updated = {
      ...caseData,
      tasks: [...(caseData.tasks || []), ...reminders],
    };
    updated = addActivity(updated, `${reminders.length} reminder task(s) generated`);
    onUpdateCase(updated);
  };

  const handleMarkItemDone = (stageId: string, itemId: string, taskType?: TaskType) => {
    setCompletingItem(itemId);
    setTimeout(() => {
      if (taskType) {
        const existing = (caseData.tasks || []).find(t => t.type === taskType && t.status !== 'completed');
        if (existing) {
          const updated = {
            ...caseData,
            tasks: (caseData.tasks || []).map(t =>
              t.id === existing.id
                ? { ...t, status: 'completed' as const, completedDate: new Date().toISOString() }
                : t
            ),
          };
          onUpdateCase(updated);
        } else {
          const newTask: CaseTask = {
            id: `wf-done-${taskType}-${Date.now()}`,
            caseId: caseData.id,
            title: `${taskType.replace(/_/g, ' ')} completed`,
            type: taskType,
            status: 'completed',
            dueDate: new Date().toISOString().split('T')[0],
            completedDate: new Date().toISOString(),
            priority: 'medium',
            recurrence: 'one-time',
            createdAt: new Date().toISOString(),
            autoGenerated: true,
          };
          const updated = {
            ...caseData,
            tasks: [...(caseData.tasks || []), newTask],
          };
          onUpdateCase(updated);
        }
      }
      setCompletingItem(null);
    }, 300);
  };

  const openTaskCount = (caseData.tasks || []).filter(t => t.status !== 'completed').length;
  const overdueCount = (caseData.tasks || []).filter(t => {
    if (t.status === 'completed') return false;
    return new Date(t.dueDate) < new Date();
  }).length;

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-2xl border border-slate-200 p-6">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h3 className="font-bold text-slate-900 text-lg">Case Workflow</h3>
            <p className="text-sm text-slate-500 mt-0.5">
              {completedItems} of {totalItems} steps completed
              {overdueCount > 0 && (
                <span className="ml-2 text-rose-600 font-medium">· {overdueCount} overdue</span>
              )}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCheckReminders}
              className="px-3.5 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors flex items-center gap-1.5"
            >
              <svg className="w-4 h-4 text-amber-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" /></svg>
              Check Reminders
            </button>
            {!caseData.workflowInitialized && (
              <button
                onClick={handleGenerateTasks}
                className="px-3.5 py-2 text-sm font-medium bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-1.5 shadow-sm"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                Initialize Workflow
              </button>
            )}
          </div>
        </div>

        <div className="mb-2 flex items-center justify-between">
          <span className="text-xs text-slate-500">Overall Progress</span>
          <span className="text-xs font-bold text-slate-700">{overallPct}%</span>
        </div>
        <div className="h-2 bg-slate-100 rounded-full overflow-hidden mb-6">
          <div
            className="h-full bg-gradient-to-r from-blue-500 to-emerald-500 rounded-full transition-all duration-700"
            style={{ width: `${overallPct}%` }}
          />
        </div>

        <div className="flex items-start gap-0 overflow-x-auto pb-2">
          {stages.map((stage, idx) => (
            <React.Fragment key={stage.stage}>
              <button
                onClick={() => setExpandedStage(expandedStage === stage.stage ? null : stage.stage)}
                className="flex flex-col items-center flex-shrink-0 group"
                style={{ minWidth: 80 }}
              >
                <div className={`w-10 h-10 rounded-full border-2 flex items-center justify-center transition-all shadow-sm ${STATUS_COLORS[stage.status]}`}>
                  {stage.status === 'complete' ? (
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" /></svg>
                  ) : stage.status === 'active' ? (
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={stage.icon} /></svg>
                  ) : (
                    <span className="text-xs font-bold">{idx + 1}</span>
                  )}
                </div>
                <span className={`text-[10px] font-semibold mt-1.5 text-center leading-tight transition-colors ${stage.status === 'complete' ? 'text-emerald-600' : stage.status === 'active' ? 'text-blue-700' : 'text-slate-400'}`}>
                  {stage.label}
                </span>
                {stage.status !== 'complete' && stage.status !== 'blocked' && (
                  <span className="text-[10px] text-slate-400">{stage.completedItems}/{stage.totalItems}</span>
                )}
              </button>
              {idx < stages.length - 1 && (
                <div className={`flex-1 h-0.5 mt-5 mx-1 min-w-3 rounded-full ${STATUS_CONNECTOR[stages[idx + 1].status]}`} />
              )}
            </React.Fragment>
          ))}
        </div>
      </div>

      {stages.map(stage => (
        expandedStage === stage.stage || stage.status === 'active' ? (
          <div key={stage.stage} className={`bg-white rounded-2xl border overflow-hidden ${stage.status === 'active' ? 'border-blue-200 shadow-sm shadow-blue-50' : 'border-slate-200'}`}>
            <div
              className={`flex items-center justify-between px-6 py-4 cursor-pointer ${stage.status === 'active' ? 'bg-blue-50' : 'bg-slate-50'}`}
              onClick={() => setExpandedStage(expandedStage === stage.stage ? null : stage.stage)}
            >
              <div className="flex items-center gap-3">
                <div className={`w-7 h-7 rounded-full flex items-center justify-center ${STATUS_COLORS[stage.status]}`}>
                  {stage.status === 'complete' ? (
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" /></svg>
                  ) : (
                    <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={stage.icon} /></svg>
                  )}
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-slate-900">{stage.label}</span>
                    {stage.status === 'active' && (
                      <span className="text-[10px] font-bold bg-blue-100 text-blue-700 px-2 py-0.5 rounded-full uppercase tracking-wide">Current</span>
                    )}
                    {stage.status === 'complete' && (
                      <span className="text-[10px] font-bold bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full uppercase tracking-wide">Complete</span>
                    )}
                  </div>
                  <p className="text-xs text-slate-500 mt-0.5">{stage.description}</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="text-right">
                  <span className="text-sm font-bold text-slate-700">{stage.completedItems}/{stage.totalItems}</span>
                </div>
                <svg className={`w-4 h-4 text-slate-400 transition-transform ${expandedStage === stage.stage ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
              </div>
            </div>

            {(expandedStage === stage.stage) && (
              <div className="divide-y divide-slate-50">
                {stage.items.map(item => (
                  <div
                    key={item.id}
                    className={`flex items-center gap-4 px-6 py-3.5 ${item.done ? 'bg-white' : item.urgent ? 'bg-amber-50' : 'bg-white'}`}
                  >
                    <button
                      onClick={() => !item.done && item.taskType && handleMarkItemDone(stage.stage, item.id, item.taskType)}
                      className={`flex-shrink-0 w-5 h-5 rounded-full border-2 flex items-center justify-center transition-all ${
                        item.done
                          ? 'bg-emerald-500 border-emerald-500'
                          : completingItem === item.id
                          ? 'border-emerald-400 bg-emerald-50'
                          : item.urgent
                          ? 'border-amber-400 hover:bg-amber-50'
                          : item.taskType
                          ? 'border-slate-300 hover:border-blue-400 hover:bg-blue-50'
                          : 'border-slate-200 cursor-default'
                      }`}
                    >
                      {item.done && (
                        <svg className="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" /></svg>
                      )}
                    </button>
                    <div className="flex-1 min-w-0">
                      <span className={`text-sm ${item.done ? 'text-slate-400 line-through' : 'text-slate-800 font-medium'}`}>
                        {item.label}
                      </span>
                      {item.detail && !item.done && (
                        <p className={`text-xs mt-0.5 ${item.urgent ? 'text-amber-600 font-medium' : 'text-slate-400'}`}>{item.detail}</p>
                      )}
                    </div>
                    {item.urgent && !item.done && (
                      <span className="flex-shrink-0 text-[10px] font-bold bg-amber-100 text-amber-700 px-2 py-0.5 rounded-full uppercase">Follow Up</span>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        ) : null
      ))}

      <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden">
        <button
          className="w-full flex items-center justify-between px-6 py-4 hover:bg-slate-50 transition-colors"
          onClick={() => setExpandedStage(expandedStage === '__all__' ? null : '__all__')}
        >
          <span className="font-semibold text-slate-700 text-sm">All Stages</span>
          <svg className={`w-4 h-4 text-slate-400 transition-transform ${expandedStage === '__all__' ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" /></svg>
        </button>
        {expandedStage === '__all__' && (
          <div className="divide-y divide-slate-100">
            {stages.map(stage => (
              <div key={stage.stage} className="px-6 py-4">
                <div className="flex items-center gap-3 mb-3">
                  <div className={`w-6 h-6 rounded-full flex items-center justify-center ${STATUS_COLORS[stage.status]}`}>
                    {stage.status === 'complete' ? (
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" /></svg>
                    ) : (
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={stage.icon} /></svg>
                    )}
                  </div>
                  <span className="font-semibold text-slate-800 text-sm">{stage.label}</span>
                  <span className="text-xs text-slate-400">{stage.completedItems}/{stage.totalItems}</span>
                </div>
                <div className="space-y-1.5 pl-9">
                  {stage.items.map(item => (
                    <div key={item.id} className="flex items-center gap-2">
                      <div className={`w-3.5 h-3.5 rounded-full flex-shrink-0 flex items-center justify-center ${item.done ? 'bg-emerald-500' : item.urgent ? 'bg-amber-200 border border-amber-400' : 'border border-slate-200'}`}>
                        {item.done && <svg className="w-2 h-2 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" /></svg>}
                      </div>
                      <span className={`text-xs ${item.done ? 'text-slate-400 line-through' : item.urgent ? 'text-amber-700 font-medium' : 'text-slate-600'}`}>{item.label}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
